[project]
name = "shiny-handouts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "ffmpeg-binaries-compat>=1.0.1",
    "jinja2>=3.1.6",
    "openai>=1.74.0",
    "opencv-python>=4.11.0.86",
    "pydub>=0.25.1",
    "requests>=2.32.3",
    "rsconnect-python>=1.25.2",
    "scikit-image>=0.25.2",
    "shiny>=1.4.0",
    "xhtml2pdf>=0.2.17",
]

[dependency-groups]
dev = [
    "lefthook>=1.11.12",
]
